#!/bin/sh
SERVICE_NAME=geophone
PATH_TO_JAR=/home/ec2-user/geophone/geophone.jar
PATH_TO_HOME=/home/ec2-user/geophone
PID_PATH_NAME=/tmp/geophone-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            cd $PATH_TO_HOME
            nohup java -jar $PATH_TO_JAR /tmp 2>> $PATH_TO_HOME/geophone.log >> $PATH_TO_HOME/geophone.log  &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            sleep 2
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            cd $PATH_TO_HOME
            nohup java -jar $PATH_TO_JAR /tmp 2>> $PATH_TO_HOME/geophone.log >> $PATH_TO_HOME/geophone.log &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
